<?php

namespace Database\Seeders;
use App\Models\jeu;
use App\Models\Poste;
use App\Models\Reservation;
use App\Models\Utilisateur;
use Illuminate\Database\Seeder;
use App\Models\categoriedesjeux;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

        //Création des categories
        categoriedesjeux::create(['categorie_nom'=>'Casse-tête']);
        categoriedesjeux::create(['categorie_nom'=>'Apocalypse']);
        categoriedesjeux::create(['categorie_nom'=>'Aventure']);
        
        //Création des postes 
        Poste::create(['poste_nomination'=>'Poste 1','poste_adresseip'=>'192.160.10.1','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 2','poste_adresseip'=>'192.160.10.2','poste_statut'=>'0']);
        Poste::create(['poste_nomination'=>'Poste 3','poste_adresseip'=>'192.160.10.3','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 4','poste_adresseip'=>'192.160.10.4','poste_statut'=>'0']);
        Poste::create(['poste_nomination'=>'Poste 5','poste_adresseip'=>'192.160.10.5','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 6','poste_adresseip'=>'192.160.10.6','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 7','poste_adresseip'=>'192.160.10.7','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 8','poste_adresseip'=>'192.160.10.8','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 9','poste_adresseip'=>'192.160.10.9','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 10','poste_adresseip'=>'192.160.10.10','poste_statut'=>'0']);
        Poste::create(['poste_nomination'=>'Poste 11','poste_adresseip'=>'192.160.10.11','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 12','poste_adresseip'=>'192.160.10.12','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 13','poste_adresseip'=>'192.160.10.13','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 14','poste_adresseip'=>'192.160.10.14','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 15','poste_adresseip'=>'192.160.10.15','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 16','poste_adresseip'=>'192.160.10.16','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 17','poste_adresseip'=>'192.160.10.17','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 18','poste_adresseip'=>'192.160.10.18','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 19','poste_adresseip'=>'192.160.10.19','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 20','poste_adresseip'=>'192.160.10.20','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 21','poste_adresseip'=>'192.160.10.21','poste_statut'=>'1']);
        Poste::create(['poste_nomination'=>'Poste 22','poste_adresseip'=>'192.160.10.22','poste_statut'=>'1']);


        
        // Création des jeux
       jeu::create(['jeu_nom' => 'Robinson', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu1.jpg','jeu_teaser' => 'public/videos/Jeux/jeu1.mp4', 'jeu_editeur'=>'Kader', 'jeu_age_minimum'=>'12','jeu_duree_minimale'=>'20','jeu_duree_maximale'=>'45','jeu_tarif'=>'5000','jeu_nombre_min_joueurs'=>'2','jeu_nombre_max_joueurs'=>'6','categoriedesjeux_id'=>'1']);
       jeu::create(['jeu_nom' => 'Resident evil', 'jeu_description' => 'En Février 1928. Une expédition dirigée par Sir Beldon Frye a disparu quelque part dans la péninsule du Sinaï...Découvrez ce qui est arrivé aux explorateurs. Et plus important encore : localisez ce qu’ils recherchaient ! ','jeu_image' => 'images/Jeux/jeu2.jpg','jeu_teaser' => '1RYaBQERMBE', 'jeu_editeur'=>'Kader', 'jeu_age_minimum'=>'15','jeu_duree_minimale'=>'25','jeu_duree_maximale'=>'40','jeu_tarif'=>'5000','jeu_nombre_min_joueurs'=>'2','jeu_nombre_max_joueurs'=>'6','categoriedesjeux_id'=>'2']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu3.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'12','jeu_duree_minimale'=>'30','jeu_duree_maximale'=>'50','jeu_tarif'=>'8000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'3']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu4.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'18','jeu_duree_minimale'=>'30','jeu_duree_maximale'=>'50','jeu_tarif'=>'5000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'1']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu5.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'10','jeu_duree_minimale'=>'20','jeu_duree_maximale'=>'45','jeu_tarif'=>'4000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'2']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu6.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'12','jeu_duree_minimale'=>'10','jeu_duree_maximale'=>'50','jeu_tarif'=>'6000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'3']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu7.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'13','jeu_duree_minimale'=>'30','jeu_duree_maximale'=>'40','jeu_tarif'=>'3000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'2']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu8.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'15','jeu_duree_minimale'=>'15','jeu_duree_maximale'=>'50','jeu_tarif'=>'10000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'1']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu9.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'12','jeu_duree_minimale'=>'20','jeu_duree_maximale'=>'50','jeu_tarif'=>'7000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'3']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu10.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'11','jeu_duree_minimale'=>'25','jeu_duree_maximale'=>'35','jeu_tarif'=>'1000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'1']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu11.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'12','jeu_duree_minimale'=>'35','jeu_duree_maximale'=>'50','jeu_tarif'=>'8000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'2']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu12.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'20','jeu_duree_minimale'=>'30','jeu_duree_maximale'=>'50','jeu_tarif'=>'2000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'3']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu13.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'12','jeu_duree_minimale'=>'20','jeu_duree_maximale'=>'45','jeu_tarif'=>'8000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'1']);
       jeu::create(['jeu_nom' => 'Assassin creed', 'jeu_description' => 'Jeu attractif','jeu_image' => 'images/Jeux/jeu14.jpg','jeu_teaser' => 'public/videos/Jeux/jeu3.mp4', 'jeu_editeur'=>'UBISOFT', 'jeu_age_minimum'=>'16','jeu_duree_minimale'=>'30','jeu_duree_maximale'=>'40','jeu_tarif'=>'8000','jeu_nombre_min_joueurs'=>'1','jeu_nombre_max_joueurs'=>'3','categoriedesjeux_id'=>'2']);

       //Création des utilisateurs
       Utilisateur::create(['utilisateur_nom'=>'CHITOU','utilisateur_prenom'=>'Kader','utilisateur_telephone'=>'61555112','utilisateur_email'=>'kaderchitou98@gmail.com','utilisateur_password'=> Hash::make('kader'),'utilisateur_date_inscription'=>'1','utilisateur_statut_inscription'=>'20/02/2022']);
       Utilisateur::create(['utilisateur_nom'=>'ADO','utilisateur_prenom'=>'Kader','utilisateur_telephone'=>'61555111','utilisateur_email'=>'kaderchitou98@gmail.com','utilisateur_password'=> Hash::make('kader1'),'utilisateur_date_inscription'=>'1','utilisateur_statut_inscription'=>'15/05/2022']);
       Utilisateur::create(['utilisateur_nom'=>'EDOH','utilisateur_prenom'=>'Kader','utilisateur_telephone'=>'61555182','utilisateur_email'=>'kaderchitou9@gmail.com','utilisateur_password'=> Hash::make('kader2'),'utilisateur_date_inscription'=>'1','utilisateur_statut_inscription'=>'20/02/2022']);
       Utilisateur::create(['utilisateur_nom'=>'ATTA','utilisateur_prenom'=>'Kader','utilisateur_telephone'=>'61555712','utilisateur_email'=>'kaderchitou8@gmail.com','utilisateur_password'=> Hash::make('kader3'),'utilisateur_date_inscription'=>'0','utilisateur_statut_inscription'=>'23/07/2022']);
       Utilisateur::create(['utilisateur_nom'=>'LEGBA','utilisateur_prenom'=>'Kader','utilisateur_telephone'=>'61585112','utilisateur_email'=>'kaderchitou58@gmail.com','utilisateur_password'=> Hash::make('kader4'),'utilisateur_date_inscription'=>'0','utilisateur_statut_inscription'=>'03/12/2022']);
       Utilisateur::create(['utilisateur_nom'=>'TOSSOU','utilisateur_prenom'=>'Fèmi','utilisateur_telephone'=>'61559112','utilisateur_email'=>'kaderchitou48@gmail.com','utilisateur_password'=> Hash::make('kader5'),'utilisateur_date_inscription'=>'0','utilisateur_statut_inscription'=>'30/01/2022']);
       Utilisateur::create(['utilisateur_nom'=>'CHITOU','utilisateur_prenom'=>'Riad','utilisateur_telephone'=>'61557112','utilisateur_email'=>'kaderchitou99@gmail.com','utilisateur_password'=> Hash::make('kader6'),'utilisateur_date_inscription'=>'0','utilisateur_statut_inscription'=>'26/02/2022']);
       

       //Création des réservations
       Reservation::create(['reservation_date'=>'2023-03-24','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'4','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'4','jeu_id'=>'2','promotion_id'=>'4', 'panier_id'=>'1']);
       Reservation::create(['reservation_date'=>'2023-03-24','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'4','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'4','jeu_id'=>'2','promotion_id'=>'4', 'panier_id'=>'1']);  
       Reservation::create(['reservation_date'=>'2023-03-24','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'4','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'4','jeu_id'=>'2','promotion_id'=>'4', 'panier_id'=>'1']); 
       Reservation::create(['reservation_date'=>'2023-03-24','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'4','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'4','jeu_id'=>'2','promotion_id'=>'4', 'panier_id'=>'1']); 
       Reservation::create(['reservation_date'=>'2023-03-24','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'4','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'4','jeu_id'=>'2','promotion_id'=>'4', 'panier_id'=>'1']); 
        Reservation::create(['reservation_date'=>'2023-03-24','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'2','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'2','jeu_id'=>'2','promotion_id'=>'4', 'panier_id'=>'1']); 

        Reservation::create(['reservation_date'=>'2023-03-25','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'4','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'4','jeu_id'=>'2','promotion_id'=>'4', 'panier_id'=>'1']);
        Reservation::create(['reservation_date'=>'2023-03-25','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'1','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'20000','utilisateur_id'=>'1','jeu_id'=>'1','promotion_id'=>'4', 'panier_id'=>'2']);
        Reservation::create(['reservation_date'=>'2023-03-25','reservation_heure_debut'=>'18:00:00','reservation_heure_fin'=>'19:00:00','reservation_nombre_personne'=>'2','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'32000','utilisateur_id'=>'2','jeu_id'=>'3','promotion_id'=>'4', 'panier_id'=>'3']);
        Reservation::create(['reservation_date'=>'2023-03-25','reservation_heure_debut'=>'18:00:00','reservation_heure_fin'=>'19:00:00','reservation_nombre_personne'=>'3','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'29000','utilisateur_id'=>'3','jeu_id'=>'5','promotion_id'=>'4', 'panier_id'=>'1']);
        Reservation::create(['reservation_date'=>'2023-03-25','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'5','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'25000','utilisateur_id'=>'5','jeu_id'=>'12','promotion_id'=>'4', 'panier_id'=>'5']);
        Reservation::create(['reservation_date'=>'2023-03-25','reservation_heure_debut'=>'19:00:00','reservation_heure_fin'=>'20:00:00','reservation_nombre_personne'=>'1','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'1','jeu_id'=>'10','promotion_id'=>'4', 'panier_id'=>'6']);
        Reservation::create(['reservation_date'=>'2023-03-25','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'2','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'32000','utilisateur_id'=>'4','jeu_id'=>'9','promotion_id'=>'4', 'panier_id'=>'2']);
        Reservation::create(['reservation_date'=>'2023-03-25','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'3','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'38000','utilisateur_id'=>'2','jeu_id'=>'5','promotion_id'=>'4', 'panier_id'=>'4']);
        Reservation::create(['reservation_date'=>'2023-03-25','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'1','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'38000','utilisateur_id'=>'2','jeu_id'=>'5','promotion_id'=>'4', 'panier_id'=>'4']);
        
        Reservation::create(['reservation_date'=>'2023-03-26','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'4','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'4','jeu_id'=>'2','promotion_id'=>'4', 'panier_id'=>'1']);
        Reservation::create(['reservation_date'=>'2023-03-26','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'1','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'20000','utilisateur_id'=>'1','jeu_id'=>'1','promotion_id'=>'4', 'panier_id'=>'2']);
        Reservation::create(['reservation_date'=>'2023-03-26','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'2','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'32000','utilisateur_id'=>'2','jeu_id'=>'3','promotion_id'=>'4', 'panier_id'=>'3']);
        Reservation::create(['reservation_date'=>'2023-03-26','reservation_heure_debut'=>'18:00:00','reservation_heure_fin'=>'19:00:00','reservation_nombre_personne'=>'3','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'29000','utilisateur_id'=>'3','jeu_id'=>'5','promotion_id'=>'4', 'panier_id'=>'1']);
        Reservation::create(['reservation_date'=>'2023-03-26','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'3','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'25000','utilisateur_id'=>'5','jeu_id'=>'12','promotion_id'=>'4', 'panier_id'=>'5']);
        Reservation::create(['reservation_date'=>'2023-03-26','reservation_heure_debut'=>'19:00:00','reservation_heure_fin'=>'20:00:00','reservation_nombre_personne'=>'2','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'1','jeu_id'=>'10','promotion_id'=>'4', 'panier_id'=>'6']);
        Reservation::create(['reservation_date'=>'2023-03-26','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'2','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'32000','utilisateur_id'=>'4','jeu_id'=>'9','promotion_id'=>'4', 'panier_id'=>'2']);
        Reservation::create(['reservation_date'=>'2023-03-26','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'4','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'38000','utilisateur_id'=>'2','jeu_id'=>'5','promotion_id'=>'4', 'panier_id'=>'4']);
        Reservation::create(['reservation_date'=>'2023-03-26','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'1','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'38000','utilisateur_id'=>'2','jeu_id'=>'5','promotion_id'=>'4', 'panier_id'=>'4']);

        Reservation::create(['reservation_date'=>'2023-03-27','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'4','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'4','jeu_id'=>'2','promotion_id'=>'4', 'panier_id'=>'1']);
        Reservation::create(['reservation_date'=>'2023-03-27','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'1','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'20000','utilisateur_id'=>'1','jeu_id'=>'1','promotion_id'=>'4', 'panier_id'=>'2']);
        Reservation::create(['reservation_date'=>'2023-03-27','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'5','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'32000','utilisateur_id'=>'2','jeu_id'=>'3','promotion_id'=>'4', 'panier_id'=>'3']);
        Reservation::create(['reservation_date'=>'2023-03-27','reservation_heure_debut'=>'18:00:00','reservation_heure_fin'=>'19:00:00','reservation_nombre_personne'=>'3','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'29000','utilisateur_id'=>'3','jeu_id'=>'5','promotion_id'=>'4', 'panier_id'=>'1']);
        Reservation::create(['reservation_date'=>'2023-03-27','reservation_heure_debut'=>'16:00:00','reservation_heure_fin'=>'17:00:00','reservation_nombre_personne'=>'1','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'25000','utilisateur_id'=>'5','jeu_id'=>'12','promotion_id'=>'4', 'panier_id'=>'5']);
        Reservation::create(['reservation_date'=>'2023-03-27','reservation_heure_debut'=>'19:00:00','reservation_heure_fin'=>'20:00:00','reservation_nombre_personne'=>'3','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'24000','utilisateur_id'=>'1','jeu_id'=>'10','promotion_id'=>'4', 'panier_id'=>'6']);
        Reservation::create(['reservation_date'=>'2023-03-27','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'2','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'32000','utilisateur_id'=>'4','jeu_id'=>'9','promotion_id'=>'4', 'panier_id'=>'2']);
        Reservation::create(['reservation_date'=>'2023-03-27','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'4','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'38000','utilisateur_id'=>'2','jeu_id'=>'5','promotion_id'=>'4', 'panier_id'=>'4']);
        Reservation::create(['reservation_date'=>'2023-03-27','reservation_heure_debut'=>'17:00:00','reservation_heure_fin'=>'18:00:00','reservation_nombre_personne'=>'2','reservation_commentaire'=>'Merci de nous rendre disponible les postes','reservation_statutDeLaReservation'=>'0','reservation_source'=>'En ligne','reservation_cout_total'=>'38000','utilisateur_id'=>'2','jeu_id'=>'5','promotion_id'=>'4', 'panier_id'=>'4']);
    }
}
     